### ISSUE TITLE
Exit code

### ISSUE THREAD

**Issue by datamuc** [RincewindsHat/monitoring_plugin_guidelines#2]
https://github.com/monitoring-plugins/monitoring-plugin-guidelines/blob/2a3bda0dba65fe0c30c87277b4c07bac46a3c604/monitoring_plugins_interface/03.Output.md?plain=1#L16

We should consider this:

https://tldp.org/LDP/abs/html/exitcodes.html

According to the above table, exit codes 1 - 2, 126 - 165, and 255 [[1]](https://tldp.org/LDP/abs/html/exitcodes.html#FTN.AEN23629) have special meanings, and should therefore be avoided for user-specified exit parameters.

I think it's ok to reuse 1 and 2 but 126 - 165 and 255 is reserved.

I think we are ok if we reserve 4-125.

**Comment by RincewindsHat** [comment]
the link seems to be an explanation of exit codes for `bash` only (correct me if I am wrong).
I can not find a comprehensive guide as to what are "valid" exit codes and what are not.
Linux seems to be limited to one byte, windows uses two (I think).

I'm fine with limiting the "future use" section to 125, that should give us enough head room to expand (if that ever happens), but the rest should be marked as "don't use (intentionally)"

**Comment by datamuc** [comment]
Sure, it's about bash. But the opengroup has a similar thing:

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html

0-125 is free to use.

**Comment by RincewindsHat** [comment]
which is once again for a shell, not why we should be limited to.
I just used the range until 255, because I am mostly sure, that that is something present in every relevant operating system.

**Comment by datamuc** [comment]
Naemon and Nagios run the commands through the shell (they  try to avoid it probably, but as soon as some funnty shell characters appear in the command that stuff is run through the `sh -c`, and then the exit code of the plugin might be masked.

**Comment by RincewindsHat** [comment]
ah, didn't know that. I somehow just assumed everybody would do a `exec*`. In that case you have good point and this should be limited to the range you mentioned.

**Comment by RincewindsHat** [comment]
close by #5
