### ISSUE TITLE
performance data

### ISSUE THREAD

**Issue by datamuc** [RincewindsHat/monitoring_plugin_guidelines#4]
https://github.com/monitoring-plugins/monitoring-plugin-guidelines/blob/2a3bda0dba65fe0c30c87277b4c07bac46a3c604/monitoring_plugins_interface/03.Output.md?plain=1#L63

The "end of the line" part applies only to the first line of the output. For the extended output it is until EOF:

https://www.naemon.io/documentation/usersguide/pluginapi.html#plugin_output_spec
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/pluginapi.html

Icinga says something different:

https://icinga.com/docs/icinga-2/latest/doc/05-service-monitoring/#performance-data-metrics

It looks like it's just separating the whole output once on the pipe,  without special handling of the first line, that's at least how i read the docs. If that is the case, a portable plugin would just follow the icinga spec and avoid any extra pipes in the first line.

**Comment by RincewindsHat** [comment]
Thanks for the research, your proposal sounds good. Attaching all performance data at the end should be the safest and most compatible way.
